### ISSUE TITLE
linalg - EXC_BAD_ACCESS: np.linalg.inv

### ISSUE THREAD

**Issue by 1agora** [kewlbear/NumPy-iOS#2]
i am getting EXC_BAD_ACCESS running the following code:

`print(odometry)`

`[[ 0.84653428 -0.0890643  -0.5248307   0.11228379]
 [ 0.04641337  0.99449876 -0.09390424  0.02433897]
 [ 0.530307    0.055134    0.84601107  0.03576265]
 [ 0.          0.          0.          1.        ]]`

 `let inv = np.linalg.inv(odometry) //EXC_BAD_ACCESS`

any help appreciated 🙏

**Comment by kewlbear** [comment]
Fixed.  Please try after updating the package.

**Comment by 1agora** [comment]
works! thanks :)
