### ISSUE TITLE
Used with iPad air4 got a error

### ISSUE THREAD

**Issue by herryliq** [kewlbear/NumPy-iOS#3]
Showing Recent Messages
'/Users/herryliq/Library/Developer/Xcode/DerivedData/Example-bqnbyojkvoxhdfcptdgyoanshrsi/Build/Products/Debug-iphoneos/libpython3.8.a(ceval.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

**Comment by kewlbear** [comment]
Bitcode is not supported.  Please turn off bitcode.

**Comment by herryliq** [comment]
Thanks for your reply.

With  turn off bitcode, I can run the Example project in iPad air4.
