### ISSUE TITLE
Error when trying to build and run the app

### ISSUE THREAD

**Issue by VotusX** [kewlbear/NumPy-iOS#5]
Hello,

I successfully managed to install the swift package on my project and also had no problem importing the modules and the initialization code also produces no error. But when I try to build the project I get the following error:

```
Link "Project name" (arm64)

Undefined symbols for architecture arm64:
  "_ffi_type_longdouble", referenced from:
      _formattable in libpython3.a(cfield.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

In short:
`Undefined symbol: _ffi_type_longdouble`

I have tried various things such as deleting derived data, cleaning the build folder and reinstalling PythonKit and Python-iOS but none of these worked out. I'm using Swift 5 on Xcode 13.2.1.

Help would be greatly appreciated.

**Comment by kewlbear** [comment]
If you are running an iOS simulator on Apple Silicon Macs, you should run Xcode using rosetta for now.

**Comment by VotusX** [comment]
I'm not on a Silicon Mac. Is there any other way around this?

**Comment by kewlbear** [comment]
Then try setting "Build Active Architectures Only" to "Yes".

**Comment by VotusX** [comment]
It‘s compiling now, thanks.

**Comment by juanjovn** [comment]
Do you know if there is a solution now for running in Simulator in Apple Silicon rather than executing with Rosetta?
