### ISSUE TITLE
"Module 'NumPySupport' has no member named 'sitePackageUrl'"

### ISSUE THREAD

**Issue by alisonqiu** [kewlbear/NumPy-iOS#8]
Just following up on the discussion over [here](https://github.com/pvieito/PythonKit/pull/30).
The example app was using SwiftUI but I wanted to use `NumPySupport.sitePackagesURL.insertPythonPath()` in the `didFinishLaunchingWithOptions `in my AppDelegate. Is this supported? I wonder if this is why I've been getting the error "Module 'NumPySupport' has no member named 'sitePackageUrl'"
<img width="862" alt="Screenshot 2023-03-21 at 7 30 20 PM" src="https://user-images.githubusercontent.com/90943803/226771652-0a96a091-9d1e-488f-a72b-bbaa62958409.png">

**Comment by kewlbear** [comment]
As I said previously, if you use this package using Swift package manager this member is automatically provided.  See https://github.com/kewlbear/NumPy-iOS/blob/c27e79ea5485f5b727aaaf330635f7d423513100/Sources/NumPySupport/SwiftBundle.swift#L27.

But if you are manually setting up your project, you have to add site-packages directory and its content to your app, and add the path to `sys.path` of Python runtime.  See https://github.com/kewlbear/Python-iOS/blob/48da31fc0fbf649f078058a9a69e8b059f4ad298/Sources/PythonSupport/SwiftBundle.swift#L120.
